name: Deploy_ARM

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of the Azure Resource Group to deploy'
        required: true
        type: string
      location:
        description: 'Azure region to deploy resources in'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      # Ensure resource group exists
      - name: Deploy Resource Group
        uses: Azure/CLI@v1
        with:
          inlinescript: |
            #!/bin/bash
            az group create --resource-group ${{ github.event.inputs.resourceGroupName }} --location ${{ github.event.inputs.location }}

      # Deploy template with PowerShell
      #- name: Deploy ARM Template
      #  uses: azure/powershell@v1
      #  env:
      #    #SSH_KEY: ${{ secrets.RJMLAB_SSH_PUB_KEY }}
      #    SSH_IP: ${{ secrets.SOURCE_IP_ADDRESS }}
      #  with:
      #    inlineScript: |
      #      #$adminPw = ConvertTo-SecureString -String "$env:SSH_KEY" -AsPlainText -Force
      #      New-AzResourceGroupDeployment `
      #      -ResourceGroupName ${{ github.event.inputs.resourceGroupName }} `
      #      -TemplateFile ${{ github.workspace }}\azuredeploy.json `
      #      -TemplateParameterFile ${{ github.workspace }}\azuredeploy.parameters.json `
      #      -location ${{ github.event.inputs.location }} `
      #      -adminPublicKey ${{ secrets.RJMLAB_SSH_PUB_KEY }} `
      #      #-networkSecurityGroupSshSourceIP "$env:SSH_IP"
      #    azPSVersion: "latest"

      # Deploy template
      - name: Deploy ARM Template
        uses: Azure/arm-deploy@v1
        env:
          SSH_KEY: ${{ secrets.RJMLAB_SSH_PUB_KEY }}
          SSH_IP: ${{ secrets.SOURCE_IP_ADDRESS }}
        with:
          resourceGroupName: ${{ github.event.inputs.ResourceGroupName }}
          template: azuredeploy.json
          parameters: azuredeploy.parameters.json location=${{ github.event.inputs.location }} adminPublicKey="${SSH_KEY}" #networkSecurityGroupSshSourceIP="${SSH_IP}"