name: Deploy_ARM

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of the Azure Resource Group to deploy'
        required: true
        type: string
      location:
        description: 'Azure region to deploy resources in'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      # Ensure resource group exists
      - name: Deploy Resource Group
        uses: Azure/CLI@v1
        with:
          inlinescript: |
            #!/bin/bash
            az group create --resource-group ${{ github.event.inputs.resourceGroupName }} --location ${{ github.event.inputs.location }}

      # Deploy template
      - name: Deploy ARM Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ github.event.inputs.ResourceGroupName }}
          template: azuredeploy.json
          parameters: azuredeploy.parameters.json location=${{ github.event.inputs.location }} adminPublicKey='${{ secrets.RJMLAB_SSH_PUB_KEY }}'